version: 2.1

commands:
  setup_sbt:
    description: Get and install SBT
    parameters:
      sbt_version:
        type: string
        default: "1.11.4"
    steps:
      - restore_cache:
          keys:
          - &sbt_cache_key sbt-{{ checksum "project/build.properties" }}

      - run:
          name: Setup SBT
          command: |
                    if [ ! -x ~/sbt/bin/sbt ]; then
                      cd ~/
                      curl --silent -L -o sbt.tgz https://github.com/sbt/sbt/releases/download/v<< parameters.sbt_version >>/sbt-<< parameters.sbt_version >>.tgz
                      tar -xzvf sbt.tgz && rm -f sbt.tgz
                    fi

      - save_cache:
          paths:
            - ~/sbt
          key: *sbt_cache_key

  build:
    description: Build
    steps:
      - restore_cache:
          keys:
          - &scala_cache_key scala-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Shaded.scala" }}

      - run:
          name: Build & Run tests
          command: |
                    export PATH=$PATH:~/sbt/bin
                    export USER=`basename $HOME`
                    
                    sbt +publishLocal

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.coursier/cache
            - ~/.sbt
          key: *scala_cache_key

jobs:
  jdk8:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_sbt
      - build

  publish_snapshots:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_sbt

      - restore_cache:
          keys:
          - *scala_cache_key

      - run:
          name: Update dependencies
          command: sbt +update

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.coursier/cache
            - ~/.sbt
          key: *scala_cache_key

      - deploy:
          name: Publish artifacts to Sonatype Snapshots
          command: |
                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
                      echo "Skipped on branch ${CIRCLE_BRANCH}"
                      exit 0
                    fi

                    V=`SBT_OPTS="-Dsbt.log.noformat=true" sbt 'show version' 2>&1 | tail -n 1 | cut -d ']' -f 2 | perl -pe 's/^[ \t]+//;s/[ \t]+$//'`

                    if [ `echo "$V" | grep -cE 'SNAPSHOT$'` -ne 1 ]; then
                      echo "Cannot publish release $V"
                      exit 0
                    fi
                    
                    export PUBLISH_REPO_NAME="Sonatype Nexus Repository Manager"
                    export PUBLISH_REPO_ID="central.sonatype.com"
                    export PUBLISH_REPO_URL="https://central.sonatype.com/repository/maven-snapshots/"
                    
                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
                      echo "Missing publication credentials"
                      exit 1
                    fi
                    
                    echo "Publishing artifacts"
                    
                    sbt error +publish

  trigger_dependent_builds:
    docker:
      - image: cimg/base:2020.01

    working_directory: ~/repo

    steps:
      - run:
          name: Trigger build @ ReactiveMongo-BSON
          command: |
                    curl -X POST "https://circleci.com/api/v1.1/project/github/ReactiveMongo/ReactiveMongo-BSON/build?circle-token=${REACTIVEMONGO_BSON_API_TOKEN}"

workflows:
  version: 2

  main_suite:
    jobs:
      - jdk8

      - publish_snapshots:
          filters:
            branches:
              only:
                - master
          requires:
            - jdk8

      - trigger_dependent_builds:
          filters:
            branches:
              only:
                - master
          requires:
            - publish_snapshots
